language: android
android:
components:
- platform-tools
- tools
- build-tools-19.0.0
- android-19
env:
global:
secure: O6Jl4M2X0K0IKQ8zq/Em1o5POOI4Xl4DG3qTY/QS1/E4jX0+01UpnX0MhEGWoJwqPspIjbcRaNDQCkrQ7oIt+r/hI5zM0bzXJpZ2wEnatZWb//mDoSU5Ge6kbpVk7PrJNsyuU1lkm55m1122Sj1DKuw2N8ZZxsboWiSdY1zoIdQ=
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- sudo apt-get install -y python-software-properties
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get update -y
- sudo apt-get install -y nodejs imagemagick
- sudo npm -g install cordova ionic bower gulp cordova-gen
- sudo npm install
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- gulp
- ionic platform add android
- cordova plugin add org.apache.cordova.splashscreen
- cordova plugin add org.apache.cordova.device
- cordova plugin add org.apache.cordova.dialogs
- cordova plugin add org.apache.cordova.network-information
- cordova plugin add https://github.com/driftyco/ionic-plugins-keyboard.git
- mkdir -p platforms/ios/CarCloud/Resources/icons
- mkdir -p platforms/ios/CarCloud/Resources/splash
- cordova-gen www/img/all.png "#FFF"
- ionic build android
after_success:
- bash ./.push-release.sh
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
deploy:
provider: releases
api_key:
secure: O6zuQzSv6husuKQkm3XOF2w8wMtxf6osgsN2xisZoGXJoSdk3n5abM17XI23MTzl57CsNnNnk0aASp2gkCUkMvyrXwmVY1aph61ehr6OunNvAnmXsMUF02nglKhmIzMAq7FMOtR/3f4sd1cCeROTEDpZYovFPNnsFIKgrFU4wwM=
file: platforms/android/ant-build/CordovaApp-debug.apk
on:
tags: true
all_branches: true
